on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: Git checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Another test
        run: |
          echo '::group::Test - direct'
          find folder -exec stat {} \;
          echo '::endgroup::'

      - name: Run python container
        uses: docker://python:2.7
        with:
          entrypoint: /bin/bash
          args: |
            -e -c "
            echo '::group::Test - container'
            find folder -exec stat {} \;
            echo '::endgroup::'
            "
