on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: Git checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Run python container
        uses: docker://python:2.7
        with:
          entrypoint: /bin/bash
          args: |
            -e -c "
            echo '::group::Test1'
            stat .
            echo '::endgroup::'
            echo '::group::Test2'
            python --version
            echo '::endgroup::'
            echo '::group::Test3'
            find . -exec stat {} \;
            echo '::endgroup::'
            "
