on:
  workflow_dispatch:
    inputs:
      gh_runs_on:
        required: false
        type: string

  push:

jobs:
  build:
    runs-on: ${{ inputs.gh_runs_on || 'ubuntu-latest' }}
    strategy:
      fail-fast: false
    steps:
      - name: Git checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Another test
        run: |
          echo '::group::Test - direct'
          find folder -exec stat {} \;
          echo '::endgroup::'

      - name: Run python container
        uses: docker://python:2.7
        with:
          entrypoint: /bin/bash
          args: |
            -e -c "
            echo '::group::Test - container'
            find folder -exec stat {} \;
            echo '::endgroup::'
            "
      - name: Hostedcache
        shell: bash
        run: |
          echo "::group::find ${{ runner.tool_cache }}"
          find ${{ runner.tool_cache }}
          echo "::endgroup::"
